server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb01
    username: root
    password: 12345666
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application: # spring.application.name属性来指定应用名称，将来会作为应用的id使用
    name: user-service # 应用名称，会在Eureka中显示
mybatis:
  type-aliases-package: com.leyou.userservice.pojo
eureka:
  client:
    # 不用指定register-with-eureka和fetch-registry，因为默认是true
    # register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    # fetch-registry: false # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port}
